# Generated by Django 3.1.4 on 2021-02-22 11:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0002_trade_notes_null_true'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.FloatField()),
                ('amount', models.IntegerField(default=100, error_messages={'invalid': '“%(value)s” value must be an integer.', 'not_enough': 'you do not have enough cash balance'}, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000000)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_type', models.CharField(choices=[('AVAILABLE', 'Available'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='AVAIALBLE', max_length=32)),
                ('purchase_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.FloatField()),
                ('amount', models.IntegerField(default=100, error_messages={'invalid': '“%(value)s” value must be an integer.', 'not_enough': 'you do not have enough coin balance'}, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000000)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale_type', models.CharField(choices=[('AVAILABLE', 'Available'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='AVAILABLE', max_length=32)),
                ('sale_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_price', models.FloatField()),
                ('transaction_amount', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000000)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(choices=[('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='FULFILLED', max_length=32)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order', to='backend.purchase')),
                ('purchase_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_purchase_user', to=settings.AUTH_USER_MODEL)),
                ('sale_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_order', to='backend.sale')),
                ('sale_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_sale_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
