# Generated by Django 3.1.4 on 2021-04-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_applicationversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=99),
        ),
    ]
