# Generated by Django 3.1.4 on 2021-03-15 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210308_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cash_locked',
            field=models.FloatField(default=0, help_text='how much cash_balance a user has locked', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000000)]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='coin_locked',
            field=models.FloatField(default=0, help_text='how much coin_balance a user has locked', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000000)]),
        ),
    ]
