# Generated by Django 3.1.4 on 2021-02-22 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_purchase_sale_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='purchase_type',
            new_name='purchase_status',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='sale_type',
            new_name='sale_status',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_type',
            new_name='transaction_status',
        ),
    ]
