# Generated by Django 3.1.4 on 2021-03-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210222_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='recipient_wallet_id',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
    ]
