# Generated by Django 3.1.4 on 2021-03-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_trade_recipient_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_status',
            field=models.CharField(choices=[('AVAILABLE', 'available'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='AVAILABLE', max_length=32),
        ),
    ]
