# Generated by Django 3.1.4 on 2021-03-15 14:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210311_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order', to='backend.purchase'),
        ),
        migrations.AddField(
            model_name='trade',
            name='sale_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_order', to='backend.sale'),
        ),
        migrations.AddField(
            model_name='trade',
            name='trade_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='transaction_status',
            field=models.CharField(blank=True, choices=[('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='FULFILLED', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_type',
            field=models.CharField(blank=True, choices=[('SEND_COIN', 'Send Coin'), ('SELL_COIN', 'Sell Coin')], default='SEND_COIN', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_value',
            field=models.IntegerField(blank=True, default=100, error_messages={'invalid': '“%(value)s” value must be an integer.', 'not_enough': 'you do not have enough cash_balance'}, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000000)]),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
