# Generated by Django 3.1.4 on 2021-03-22 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='coin_locked',
            field=models.IntegerField(default=0, help_text='how much coin_balance a user has locked', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000000)]),
        ),
    ]
