# Generated by Django 3.1.4 on 2021-03-24 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210301_0929'),
        ('accounts', '0004_customuser_device'),
    ]

    operations = [
    ]
