# Generated by Django 3.1.4 on 2021-03-29 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20210324_1207'),
        ('accounts', '0005_merge_20210324_1147'),
    ]

    operations = [
    ]
